'''
    Here are all the terms we are going to download the trend data for.
    The ammount of data collected in files will be:
         total = geo_terms x periods_of_time x list_of_search_terms
    Approx: 3600 queries

'''


list_of_geo_terms = [
    "AU-ACT",
    "AU-NSW",
    # "AU-NT",
    # "AU-QLD",
    # "AU-SA",
    # "AU-TAS",
    # "AU-VIC",
    # "AU-WA",
    # "AU",
]

'''
    Periods of time consist of a start date and a number of month
'''
list_of_periods_of_time = [
    '1 2006+96m', #Jan 2006 to Dec 2009
    '1 2009+48m', #Jan 2009 to Dec 2011
]


list_of_search_terms = [
    "Barmah forest",
    "Chicken pox",
    "hep a",
    "hep b",
    "hep c",
    "Ross River",
    "a cough",
    "alphamox",
    "amoxil",
    "armah forest",
    "barmah forest virus",
    "biaxsig",
    "blood in mucus",
    "blood in phlegm",
    "blood test",
    "botulism",
    "bromhexine",
    "bronchiolitis",
    "bronchitis",
    "bronchitis contagious",
    "bruise",
    "bruise easily",
    "bruised",
    "cairns flood",
    "ceclor",
    "cervical mucus",
    "chest infection",
    "chest infections",
    "chesty",
    "chesty cough",
    "Chikungunya",
    "chilblains",
    "Chlamydia",
    "cilamox",
    "clarithromycin",
    "codeine linctus",
    "codral",
    "codral cold and flu",
    "cold and flu",
    "cold and flu tablets",
    "cold flu",
    "cold hands",
    "cold hands and feet",
    "cold symptoms",
    "colds",
    "conjunctivitis",
    "conjunctivitis contagious",
    "cough",
    "cough medicine",
    "cough remedies",
    "cough remedy",
    "cough suppressant",
    "coughs",
    "cramping",
    "cramps",
    "Cryptosporidiosis",
    "Cryptosporidium",
    "cymbalta",
    "decongestant",
    "demazin",
    "Dengue",
    "dengue fever",
    "dengue fever symptoms",
    "dengue mosquito",
    "dengue symptoms",
    "dextromethorphan",
    "dextromethorphan hydrobromide",
    "diarrhea",
    "difflam",
    "dimetapp",
    "discharge",
    "dry cough",
    "duro tuss",
    "expectorant",
    "flash floods",
    "flood",
    "flood australia",
    "flood damage",
    "flood damaged cars",
    "flood recovery",
    "Flu",
    "flu and pregnancy",
    "flu contagious",
    "flu cough",
    "flu incubation",
    "flu incubation period",
    "flu injection",
    "flu injections",
    "flu pregnancy",
    "flu shots",
    "flu symptoms",
    "flu tablets",
    "flu treatment",
    "flu vaccinations",
    "fluvax",
    "foot and",
    "foot and mouth",
    "foot and mouth disease",
    "gonococcal",
    "gonorrhea",
    "gonorrhoea",
    "h1n1 flu",
    "h1n1 vaccine",
    "hand foot",
    "hand foot and mouth",
    "hep",
    "hepatitis",
    "Hepatitis A",
    "Hepatitis B",
    "Hepatitis C",
    "hives rash",
    "hooping",
    "human temperature",
    "impetigo",
    "Influenza",
    "influenza a",
    "influenza a virus",
    "influenza symptoms",
    "influenza vaccine",
    "influvac",
    "is pneumonia",
    "is pneumonia contagious",
    "kalixocin",
    "laryngitis",
    "legionella",
    "Legionellosis",
    "legionnaires",
    "lemsip",
    "leptospirosis",
    "linctus",
    "listeria",
    "listeriosis",
    "lozenges",
    "measles",
    "measles outbreak",
    "meningitis",
    "meningococcal",
    "mouth disease",
    "Murray Valley",
    "Murray Valley encephalitis",
    "myxomatosis",
    "nasal congestion",
    "neomycin",
    "neuritis",
    "night sweats",
    "optic neuritis",
    "panvax",
    "pathology",
    "Pertussis",
    "phenomia",
    "phenylephrine",
    "phenylephrine hydrochloride",
    "pholcodine",
    "pleurisy",
    "pneumococcal",
    "pneumonia",
    "pristiq",
    "red cheeks",
    "rheumatology",
    "rikodeine",
    "robitussin",
    "ross river",
    "ross river fever",
    "ross river fever symptoms",
    "ross river virus",
    "ross river virus symptoms",
    "roxar",
    "roxithromycin",
    "rulide",
    "school sores",
    "senega",
    "senega and ammonia",
    "shingles",
    "sinus",
    "sinusitis",
    "slap face",
    "slapped cheek",
    "staph infection",
    "strepsils",
    "sudafed",
    "swine flu symptoms",
    "symptom checker",
    "symptoms of dengue",
    "symptoms of dengue fever",
    "symptoms of pneumonia",
    "symptoms of swine",
    "symptoms of swine flu",
    "tamiflu",
    "tamiflu side effects",
    "townsville flood",
    "Varicella",
    "vicks",
    "water flood",
    "white creamy discharge",
    "white discharge",
    "whooping",
    "whooping cough",
    "whooping cough in adults",
    "whooping cough treatment",
]
